import {
  Patient,
  PatientDocument,
  ExtractedEntity,
  TimelineEvent,
  ClinicalTrial,
  TrialMatch,
  CriterionEvaluation,
  AuditLogEntry,
  DashboardStats,
  MissingDataTask,
} from "./types";

// ==================== Patients ====================

export const mockPatients: Patient[] = [
  {
    id: "p-001",
    mrn: "MRN-2024-001",
    first_name: "John",
    last_name: "Doe",
    date_of_birth: "1958-03-15",
    sex: "Male",
    status: "matches_available",
    created_at: "2026-06-10T08:30:00Z",
    updated_at: "2026-06-20T14:22:00Z",
    documents_count: 3,
    notes: "Stage IIIB NSCLC patient. EGFR mutation testing pending.",
  },
  {
    id: "p-002",
    mrn: "MRN-2024-002",
    first_name: "Jane",
    last_name: "Smith",
    date_of_birth: "1972-09-22",
    sex: "Female",
    status: "under_review",
    created_at: "2026-06-12T10:15:00Z",
    updated_at: "2026-06-21T09:45:00Z",
    documents_count: 5,
    notes: "Type 2 diabetes with recent HbA1c 8.2%. On metformin 1000mg BID.",
  },
  {
    id: "p-003",
    mrn: "MRN-2024-003",
    first_name: "Maria",
    last_name: "Garcia",
    date_of_birth: "1965-11-08",
    sex: "Female",
    status: "extraction_complete",
    created_at: "2026-06-18T13:00:00Z",
    updated_at: "2026-06-22T11:30:00Z",
    documents_count: 4,
    notes: "HR+/HER2- metastatic breast cancer. Prior CDK4/6 inhibitor therapy.",
  },
];

// ==================== Documents ====================

export const mockDocuments: PatientDocument[] = [
  {
    id: "doc-001",
    patient_id: "p-001",
    filename: "pathology_report_2026.pdf",
    file_type: "application/pdf",
    file_size_bytes: 2450000,
    status: "completed",
    uploaded_at: "2026-06-10T08:35:00Z",
    processed_at: "2026-06-10T08:42:00Z",
    page_count: 8,
  },
  {
    id: "doc-002",
    patient_id: "p-001",
    filename: "lab_results_june2026.pdf",
    file_type: "application/pdf",
    file_size_bytes: 890000,
    status: "completed",
    uploaded_at: "2026-06-15T10:20:00Z",
    processed_at: "2026-06-15T10:25:00Z",
    page_count: 3,
  },
  {
    id: "doc-003",
    patient_id: "p-001",
    filename: "ct_scan_report.pdf",
    file_type: "application/pdf",
    file_size_bytes: 1200000,
    status: "processing",
    uploaded_at: "2026-06-20T14:00:00Z",
    page_count: 5,
  },
  {
    id: "doc-004",
    patient_id: "p-002",
    filename: "endocrinology_notes.pdf",
    file_type: "application/pdf",
    file_size_bytes: 1560000,
    status: "completed",
    uploaded_at: "2026-06-12T10:20:00Z",
    processed_at: "2026-06-12T10:28:00Z",
    page_count: 12,
  },
  {
    id: "doc-005",
    patient_id: "p-002",
    filename: "metabolic_panel_results.pdf",
    file_type: "application/pdf",
    file_size_bytes: 450000,
    status: "completed",
    uploaded_at: "2026-06-18T09:00:00Z",
    processed_at: "2026-06-18T09:05:00Z",
    page_count: 2,
  },
  {
    id: "doc-006",
    patient_id: "p-002",
    filename: "retinal_exam_2026.pdf",
    file_type: "application/pdf",
    file_size_bytes: 3200000,
    status: "completed",
    uploaded_at: "2026-06-19T11:30:00Z",
    processed_at: "2026-06-19T11:38:00Z",
    page_count: 6,
  },
  {
    id: "doc-007",
    patient_id: "p-002",
    filename: "cardiology_clearance.pdf",
    file_type: "application/pdf",
    file_size_bytes: 780000,
    status: "completed",
    uploaded_at: "2026-06-20T08:15:00Z",
    processed_at: "2026-06-20T08:20:00Z",
    page_count: 4,
  },
  {
    id: "doc-008",
    patient_id: "p-002",
    filename: "medication_list_current.pdf",
    file_type: "application/pdf",
    file_size_bytes: 320000,
    status: "completed",
    uploaded_at: "2026-06-21T09:00:00Z",
    processed_at: "2026-06-21T09:03:00Z",
    page_count: 1,
  },
  {
    id: "doc-009",
    patient_id: "p-003",
    filename: "oncology_consult_note.pdf",
    file_type: "application/pdf",
    file_size_bytes: 1890000,
    status: "completed",
    uploaded_at: "2026-06-18T13:10:00Z",
    processed_at: "2026-06-18T13:18:00Z",
    page_count: 10,
  },
  {
    id: "doc-010",
    patient_id: "p-003",
    filename: "breast_biopsy_report.pdf",
    file_type: "application/pdf",
    file_size_bytes: 2100000,
    status: "completed",
    uploaded_at: "2026-06-18T13:15:00Z",
    processed_at: "2026-06-18T13:25:00Z",
    page_count: 7,
  },
  {
    id: "doc-011",
    patient_id: "p-003",
    filename: "pet_ct_report.pdf",
    file_type: "application/pdf",
    file_size_bytes: 1750000,
    status: "completed",
    uploaded_at: "2026-06-20T10:00:00Z",
    processed_at: "2026-06-20T10:10:00Z",
    page_count: 9,
  },
  {
    id: "doc-012",
    patient_id: "p-003",
    filename: "genomic_panel_results.pdf",
    file_type: "application/pdf",
    file_size_bytes: 980000,
    status: "failed",
    uploaded_at: "2026-06-22T11:00:00Z",
    error_message: "Unable to parse scanned document. OCR quality too low.",
  },
];

// ==================== Extracted Entities ====================

export const mockEntities: ExtractedEntity[] = [
  // John Doe - NSCLC
  {
    id: "ent-001",
    patient_id: "p-001",
    document_id: "doc-001",
    entity_type: "diagnosis",
    name: "Non-Small Cell Lung Cancer",
    value: "Stage IIIB",
    date: "2026-05-28",
    source_snippet: "Final diagnosis: Non-small cell lung cancer (adenocarcinoma), Stage IIIB (T4N2M0)",
    page_number: 2,
    confidence: 0.96,
    is_negated: false,
  },
  {
    id: "ent-002",
    patient_id: "p-001",
    document_id: "doc-001",
    entity_type: "biomarker",
    name: "PD-L1 TPS",
    value: "60",
    unit: "%",
    date: "2026-05-28",
    source_snippet: "PD-L1 expression by IHC (22C3): Tumor Proportion Score (TPS) = 60%",
    page_number: 4,
    confidence: 0.98,
    is_negated: false,
  },
  {
    id: "ent-003",
    patient_id: "p-001",
    document_id: "doc-001",
    entity_type: "biomarker",
    name: "EGFR Mutation",
    value: "Pending",
    date: "2026-06-01",
    source_snippet: "EGFR mutation analysis: Sample sent for molecular testing, results pending",
    page_number: 5,
    confidence: 0.85,
    is_negated: false,
  },
  {
    id: "ent-004",
    patient_id: "p-001",
    document_id: "doc-001",
    entity_type: "biomarker",
    name: "ALK Rearrangement",
    value: "Negative",
    date: "2026-05-30",
    source_snippet: "ALK rearrangement by FISH: Negative",
    page_number: 5,
    confidence: 0.97,
    is_negated: true,
  },
  {
    id: "ent-005",
    patient_id: "p-001",
    document_id: "doc-002",
    entity_type: "lab_result",
    name: "Creatinine",
    value: "1.1",
    unit: "mg/dL",
    date: "2026-06-15",
    source_snippet: "Serum Creatinine: 1.1 mg/dL (ref: 0.7-1.3)",
    page_number: 1,
    confidence: 0.99,
    is_negated: false,
  },
  {
    id: "ent-006",
    patient_id: "p-001",
    document_id: "doc-002",
    entity_type: "lab_result",
    name: "ANC",
    value: "3200",
    unit: "cells/µL",
    date: "2026-06-15",
    source_snippet: "Absolute Neutrophil Count (ANC): 3,200 cells/µL (ref: 1,500-8,000)",
    page_number: 1,
    confidence: 0.99,
    is_negated: false,
  },
  {
    id: "ent-007",
    patient_id: "p-001",
    document_id: "doc-002",
    entity_type: "lab_result",
    name: "Hemoglobin",
    value: "12.8",
    unit: "g/dL",
    date: "2026-06-15",
    source_snippet: "Hemoglobin: 12.8 g/dL (ref: 13.5-17.5)",
    page_number: 1,
    confidence: 0.99,
    is_negated: false,
  },
  {
    id: "ent-008",
    patient_id: "p-001",
    document_id: "doc-002",
    entity_type: "medication",
    name: "Carboplatin",
    value: "AUC 5",
    date: "2026-06-01",
    source_snippet: "Current regimen: Carboplatin AUC 5 + Pemetrexed 500mg/m² q21d",
    page_number: 2,
    confidence: 0.94,
    is_negated: false,
  },
  // Jane Smith - Diabetes
  {
    id: "ent-009",
    patient_id: "p-002",
    document_id: "doc-004",
    entity_type: "diagnosis",
    name: "Type 2 Diabetes Mellitus",
    value: "Uncontrolled",
    date: "2026-06-12",
    source_snippet: "Assessment: Type 2 Diabetes Mellitus, inadequately controlled on current regimen",
    page_number: 3,
    confidence: 0.97,
    is_negated: false,
  },
  {
    id: "ent-010",
    patient_id: "p-002",
    document_id: "doc-005",
    entity_type: "lab_result",
    name: "HbA1c",
    value: "8.2",
    unit: "%",
    date: "2026-06-18",
    source_snippet: "Hemoglobin A1c: 8.2% (target <7.0%)",
    page_number: 1,
    confidence: 0.99,
    is_negated: false,
  },
  {
    id: "ent-011",
    patient_id: "p-002",
    document_id: "doc-005",
    entity_type: "lab_result",
    name: "Fasting Glucose",
    value: "186",
    unit: "mg/dL",
    date: "2026-06-18",
    source_snippet: "Fasting Plasma Glucose: 186 mg/dL (ref: 70-100)",
    page_number: 1,
    confidence: 0.99,
    is_negated: false,
  },
  {
    id: "ent-012",
    patient_id: "p-002",
    document_id: "doc-005",
    entity_type: "lab_result",
    name: "eGFR",
    value: "72",
    unit: "mL/min/1.73m²",
    date: "2026-06-18",
    source_snippet: "eGFR (CKD-EPI): 72 mL/min/1.73m² (ref: >60)",
    page_number: 1,
    confidence: 0.98,
    is_negated: false,
  },
  {
    id: "ent-013",
    patient_id: "p-002",
    document_id: "doc-008",
    entity_type: "medication",
    name: "Metformin",
    value: "1000mg BID",
    date: "2026-06-21",
    source_snippet: "Metformin 1000mg twice daily with meals",
    page_number: 1,
    confidence: 0.99,
    is_negated: false,
  },
  {
    id: "ent-014",
    patient_id: "p-002",
    document_id: "doc-008",
    entity_type: "medication",
    name: "Lisinopril",
    value: "10mg daily",
    date: "2026-06-21",
    source_snippet: "Lisinopril 10mg once daily",
    page_number: 1,
    confidence: 0.99,
    is_negated: false,
  },
  // Maria Garcia - Breast Cancer
  {
    id: "ent-015",
    patient_id: "p-003",
    document_id: "doc-010",
    entity_type: "diagnosis",
    name: "Invasive Ductal Carcinoma",
    value: "Metastatic",
    date: "2026-06-15",
    source_snippet: "Diagnosis: Invasive ductal carcinoma of the left breast, metastatic to bone and liver",
    page_number: 1,
    confidence: 0.97,
    is_negated: false,
  },
  {
    id: "ent-016",
    patient_id: "p-003",
    document_id: "doc-010",
    entity_type: "biomarker",
    name: "Estrogen Receptor",
    value: "Positive (85%)",
    date: "2026-06-15",
    source_snippet: "ER: Positive, 85% of tumor nuclei staining",
    page_number: 3,
    confidence: 0.98,
    is_negated: false,
  },
  {
    id: "ent-017",
    patient_id: "p-003",
    document_id: "doc-010",
    entity_type: "biomarker",
    name: "HER2",
    value: "Negative (IHC 1+)",
    date: "2026-06-15",
    source_snippet: "HER2 by IHC: 1+ (Negative). FISH not performed.",
    page_number: 3,
    confidence: 0.97,
    is_negated: true,
  },
  {
    id: "ent-018",
    patient_id: "p-003",
    document_id: "doc-009",
    entity_type: "medication",
    name: "Palbociclib",
    value: "125mg d1-21 q28d",
    date: "2026-03-01",
    source_snippet: "Prior therapy: Palbociclib 125mg days 1-21 of 28-day cycle + Letrozole. Discontinued due to progression after 8 cycles.",
    page_number: 5,
    confidence: 0.95,
    is_negated: false,
  },
  {
    id: "ent-019",
    patient_id: "p-003",
    document_id: "doc-009",
    entity_type: "biomarker",
    name: "PIK3CA Mutation",
    value: "H1047R",
    date: "2026-06-10",
    source_snippet: "Molecular testing: PIK3CA mutation detected (H1047R, pathogenic)",
    page_number: 7,
    confidence: 0.96,
    is_negated: false,
  },
];

// ==================== Timeline Events ====================

export const mockTimeline: TimelineEvent[] = [
  // John Doe
  {
    id: "tl-001",
    patient_id: "p-001",
    date: "2026-05-28",
    event_type: "diagnosis",
    title: "NSCLC Diagnosis Confirmed",
    description: "Pathology confirmed non-small cell lung cancer (adenocarcinoma), Stage IIIB (T4N2M0)",
    source: "pathology_report_2026.pdf",
  },
  {
    id: "tl-002",
    patient_id: "p-001",
    date: "2026-06-01",
    event_type: "medication",
    title: "Chemotherapy Initiated",
    description: "Started Carboplatin AUC 5 + Pemetrexed 500mg/m² every 21 days",
    source: "lab_results_june2026.pdf",
  },
  {
    id: "tl-003",
    patient_id: "p-001",
    date: "2026-06-10",
    event_type: "status_change",
    title: "Patient Enrolled in TrialMatch",
    description: "Patient record created and initial documents uploaded for screening",
  },
  {
    id: "tl-004",
    patient_id: "p-001",
    date: "2026-06-15",
    event_type: "lab_result",
    title: "Lab Results Available",
    description: "CBC and CMP results: ANC 3200, Hgb 12.8, Creatinine 1.1, Platelets 180K",
    source: "lab_results_june2026.pdf",
  },
  {
    id: "tl-005",
    patient_id: "p-001",
    date: "2026-06-20",
    event_type: "note",
    title: "CT Scan Uploaded",
    description: "Follow-up CT chest/abdomen/pelvis uploaded. Processing in progress.",
  },
  // Jane Smith
  {
    id: "tl-006",
    patient_id: "p-002",
    date: "2026-05-01",
    event_type: "diagnosis",
    title: "T2DM Diagnosis Update",
    description: "Endocrinology consultation confirmed inadequately controlled T2DM on metformin monotherapy",
    source: "endocrinology_notes.pdf",
  },
  {
    id: "tl-007",
    patient_id: "p-002",
    date: "2026-06-12",
    event_type: "status_change",
    title: "Patient Enrolled",
    description: "Patient registered for clinical trial screening",
  },
  {
    id: "tl-008",
    patient_id: "p-002",
    date: "2026-06-18",
    event_type: "lab_result",
    title: "Metabolic Panel Results",
    description: "HbA1c 8.2%, Fasting glucose 186 mg/dL, eGFR 72 mL/min/1.73m²",
    source: "metabolic_panel_results.pdf",
  },
  // Maria Garcia
  {
    id: "tl-009",
    patient_id: "p-003",
    date: "2026-03-01",
    event_type: "medication",
    title: "Palbociclib Discontinued",
    description: "CDK4/6 inhibitor therapy discontinued after disease progression on 8th cycle",
    source: "oncology_consult_note.pdf",
  },
  {
    id: "tl-010",
    patient_id: "p-003",
    date: "2026-06-10",
    event_type: "biomarker",
    title: "PIK3CA Mutation Detected",
    description: "Genomic testing identified PIK3CA H1047R pathogenic mutation",
    source: "oncology_consult_note.pdf",
  },
  {
    id: "tl-011",
    patient_id: "p-003",
    date: "2026-06-15",
    event_type: "diagnosis",
    title: "Metastatic Disease Confirmed",
    description: "Biopsy confirmed invasive ductal carcinoma metastatic to bone and liver. HR+/HER2-",
    source: "breast_biopsy_report.pdf",
  },
  {
    id: "tl-012",
    patient_id: "p-003",
    date: "2026-06-18",
    event_type: "status_change",
    title: "Enrolled for Screening",
    description: "Patient documents uploaded for clinical trial matching",
  },
];

// ==================== Clinical Trials ====================

export const mockTrials: ClinicalTrial[] = [
  {
    id: "t-001",
    nct_id: "NCT05012345",
    title: "A Phase 3 Study of Pembrolizumab Plus Chemotherapy vs Chemotherapy Alone in Participants With Advanced NSCLC",
    condition: "Non-Small Cell Lung Cancer",
    intervention: "Pembrolizumab + Platinum-based Chemotherapy",
    phase: "Phase 3",
    status: "recruiting",
    sponsor: "Merck Sharp & Dohme LLC",
    summary: "This study compares the efficacy and safety of pembrolizumab combined with platinum-based chemotherapy versus chemotherapy alone as first-line treatment in participants with stage IIIB-IV non-small cell lung cancer without EGFR or ALK genomic alterations.",
    min_age: 18,
    max_age: 85,
    sex: "All",
    healthy_volunteers: false,
    sites: [
      { id: "s-001", name: "Massachusetts General Hospital", city: "Boston", state: "MA", country: "United States", status: "Recruiting" },
      { id: "s-002", name: "MD Anderson Cancer Center", city: "Houston", state: "TX", country: "United States", status: "Recruiting" },
      { id: "s-003", name: "Memorial Sloan Kettering", city: "New York", state: "NY", country: "United States", status: "Not yet recruiting" },
    ],
    inclusion_criteria: [
      { id: "ic-001", trial_id: "t-001", criterion_type: "inclusion", category: "demographics", text: "Age ≥ 18 years at time of informed consent", order_index: 1 },
      { id: "ic-002", trial_id: "t-001", criterion_type: "inclusion", category: "diagnosis", text: "Histologically or cytologically confirmed Stage IIIB or IV non-small cell lung cancer (adenocarcinoma or squamous)", order_index: 2 },
      { id: "ic-003", trial_id: "t-001", criterion_type: "inclusion", category: "biomarkers", text: "PD-L1 Tumor Proportion Score (TPS) ≥ 50% by IHC 22C3", order_index: 3 },
      { id: "ic-004", trial_id: "t-001", criterion_type: "inclusion", category: "performance_status", text: "ECOG Performance Status 0 or 1", order_index: 4 },
      { id: "ic-005", trial_id: "t-001", criterion_type: "inclusion", category: "lab_thresholds", text: "Absolute neutrophil count (ANC) ≥ 1,500/µL", order_index: 5 },
      { id: "ic-006", trial_id: "t-001", criterion_type: "inclusion", category: "lab_thresholds", text: "Hemoglobin ≥ 9.0 g/dL", order_index: 6 },
      { id: "ic-007", trial_id: "t-001", criterion_type: "inclusion", category: "organ_function", text: "Adequate renal function: creatinine ≤ 1.5x upper limit of normal (ULN) or calculated creatinine clearance ≥ 60 mL/min", order_index: 7 },
    ],
    exclusion_criteria: [
      { id: "ec-001", trial_id: "t-001", criterion_type: "exclusion", category: "biomarkers", text: "Known EGFR sensitizing mutation or ALK translocation", order_index: 1 },
      { id: "ec-002", trial_id: "t-001", criterion_type: "exclusion", category: "prior_therapy", text: "Prior systemic therapy for metastatic NSCLC", order_index: 2 },
      { id: "ec-003", trial_id: "t-001", criterion_type: "exclusion", category: "comorbidities", text: "Active autoimmune disease requiring systemic immunosuppressive therapy within the past 2 years", order_index: 3 },
      { id: "ec-004", trial_id: "t-001", criterion_type: "exclusion", category: "medications", text: "Current use of systemic corticosteroids (>10mg daily prednisone equivalent)", order_index: 4 },
    ],
    last_updated: "2026-06-01T00:00:00Z",
  },
  {
    id: "t-002",
    nct_id: "NCT05098765",
    title: "Phase 3 Study of Tirzepatide vs Placebo in Adults With Inadequately Controlled Type 2 Diabetes",
    condition: "Type 2 Diabetes Mellitus",
    intervention: "Tirzepatide (GIP/GLP-1 receptor agonist)",
    phase: "Phase 3",
    status: "recruiting",
    sponsor: "Eli Lilly and Company",
    summary: "A randomized, double-blind, placebo-controlled study evaluating the efficacy and safety of tirzepatide in adults with type 2 diabetes mellitus inadequately controlled on metformin monotherapy.",
    min_age: 18,
    max_age: 75,
    sex: "All",
    healthy_volunteers: false,
    sites: [
      { id: "s-004", name: "Joslin Diabetes Center", city: "Boston", state: "MA", country: "United States", status: "Recruiting" },
      { id: "s-005", name: "Mayo Clinic", city: "Rochester", state: "MN", country: "United States", status: "Recruiting" },
    ],
    inclusion_criteria: [
      { id: "ic-008", trial_id: "t-002", criterion_type: "inclusion", category: "demographics", text: "Age 18 to 75 years, inclusive", order_index: 1 },
      { id: "ic-009", trial_id: "t-002", criterion_type: "inclusion", category: "diagnosis", text: "Diagnosis of Type 2 Diabetes Mellitus for at least 6 months", order_index: 2 },
      { id: "ic-010", trial_id: "t-002", criterion_type: "inclusion", category: "lab_thresholds", text: "HbA1c between 7.5% and 10.5%, inclusive, at screening", order_index: 3 },
      { id: "ic-011", trial_id: "t-002", criterion_type: "inclusion", category: "medications", text: "On stable dose of metformin (≥1000mg/day) for at least 8 weeks prior to screening", order_index: 4 },
      { id: "ic-012", trial_id: "t-002", criterion_type: "inclusion", category: "organ_function", text: "eGFR ≥ 45 mL/min/1.73m² by CKD-EPI formula", order_index: 5 },
    ],
    exclusion_criteria: [
      { id: "ec-005", trial_id: "t-002", criterion_type: "exclusion", category: "diagnosis", text: "Type 1 diabetes mellitus or history of diabetic ketoacidosis", order_index: 1 },
      { id: "ec-006", trial_id: "t-002", criterion_type: "exclusion", category: "prior_therapy", text: "Prior use of any GLP-1 receptor agonist or GIP/GLP-1 dual agonist within 3 months of screening", order_index: 2 },
      { id: "ec-007", trial_id: "t-002", criterion_type: "exclusion", category: "comorbidities", text: "History of medullary thyroid carcinoma or Multiple Endocrine Neoplasia syndrome type 2 (MEN2)", order_index: 3 },
      { id: "ec-008", trial_id: "t-002", criterion_type: "exclusion", category: "comorbidities", text: "History of pancreatitis", order_index: 4 },
    ],
    last_updated: "2026-05-15T00:00:00Z",
  },
  {
    id: "t-003",
    nct_id: "NCT05156789",
    title: "Phase 2 Study of Alpelisib + Fulvestrant in HR+/HER2- Advanced Breast Cancer With PIK3CA Mutation",
    condition: "Breast Cancer",
    intervention: "Alpelisib (PI3Kα inhibitor) + Fulvestrant",
    phase: "Phase 2",
    status: "recruiting",
    sponsor: "Novartis Pharmaceuticals",
    summary: "A single-arm, open-label study evaluating the efficacy and safety of alpelisib in combination with fulvestrant in postmenopausal women with HR+/HER2- advanced or metastatic breast cancer harboring a PIK3CA mutation, who have progressed on prior CDK4/6 inhibitor therapy.",
    min_age: 18,
    sex: "Female",
    healthy_volunteers: false,
    sites: [
      { id: "s-006", name: "Dana-Farber Cancer Institute", city: "Boston", state: "MA", country: "United States", status: "Recruiting" },
      { id: "s-007", name: "UCLA Jonsson Cancer Center", city: "Los Angeles", state: "CA", country: "United States", status: "Recruiting" },
      { id: "s-008", name: "Vanderbilt-Ingram Cancer Center", city: "Nashville", state: "TN", country: "United States", status: "Not yet recruiting" },
    ],
    inclusion_criteria: [
      { id: "ic-013", trial_id: "t-003", criterion_type: "inclusion", category: "demographics", text: "Female, age ≥ 18 years", order_index: 1 },
      { id: "ic-014", trial_id: "t-003", criterion_type: "inclusion", category: "diagnosis", text: "Histologically confirmed HR-positive (ER+ and/or PR+), HER2-negative advanced or metastatic breast cancer", order_index: 2 },
      { id: "ic-015", trial_id: "t-003", criterion_type: "inclusion", category: "biomarkers", text: "Documented PIK3CA mutation (by tissue or liquid biopsy using validated assay)", order_index: 3 },
      { id: "ic-016", trial_id: "t-003", criterion_type: "inclusion", category: "prior_therapy", text: "Disease progression on or after prior CDK4/6 inhibitor-based therapy", order_index: 4 },
      { id: "ic-017", trial_id: "t-003", criterion_type: "inclusion", category: "performance_status", text: "ECOG Performance Status 0 or 1", order_index: 5 },
      { id: "ic-018", trial_id: "t-003", criterion_type: "inclusion", category: "lab_thresholds", text: "Fasting plasma glucose ≤ 140 mg/dL and HbA1c ≤ 6.4%", order_index: 6 },
    ],
    exclusion_criteria: [
      { id: "ec-009", trial_id: "t-003", criterion_type: "exclusion", category: "comorbidities", text: "Pre-existing Type 1 or uncontrolled Type 2 diabetes mellitus (HbA1c > 6.4%)", order_index: 1 },
      { id: "ec-010", trial_id: "t-003", criterion_type: "exclusion", category: "prior_therapy", text: "Prior treatment with any PI3K, mTOR, or AKT inhibitor", order_index: 2 },
      { id: "ec-011", trial_id: "t-003", criterion_type: "exclusion", category: "comorbidities", text: "Known active inflammatory bowel disease or chronic diarrhea", order_index: 3 },
    ],
    last_updated: "2026-06-10T00:00:00Z",
  },
];

// ==================== Trial Matches ====================

const match1Evaluations: CriterionEvaluation[] = [
  {
    id: "ce-001", match_id: "m-001", criterion_id: "ic-001", criterion_text: "Age ≥ 18 years at time of informed consent",
    criterion_type: "inclusion", category: "demographics", result: "passed",
    evidence_snippet: "DOB: 1958-03-15 (Age 68)", explanation: "Patient is 68 years old, meeting the minimum age requirement of 18 years.", confidence: 1.0,
  },
  {
    id: "ce-002", match_id: "m-001", criterion_id: "ic-002", criterion_text: "Histologically or cytologically confirmed Stage IIIB or IV non-small cell lung cancer",
    criterion_type: "inclusion", category: "diagnosis", result: "passed",
    evidence_snippet: "Final diagnosis: Non-small cell lung cancer (adenocarcinoma), Stage IIIB (T4N2M0)", explanation: "Patient has histologically confirmed Stage IIIB NSCLC adenocarcinoma.", confidence: 0.96,
  },
  {
    id: "ce-003", match_id: "m-001", criterion_id: "ic-003", criterion_text: "PD-L1 Tumor Proportion Score (TPS) ≥ 50% by IHC 22C3",
    criterion_type: "inclusion", category: "biomarkers", result: "passed",
    evidence_snippet: "PD-L1 expression by IHC (22C3): Tumor Proportion Score (TPS) = 60%", explanation: "PD-L1 TPS is 60%, exceeding the 50% threshold.", confidence: 0.98,
  },
  {
    id: "ce-004", match_id: "m-001", criterion_id: "ic-004", criterion_text: "ECOG Performance Status 0 or 1",
    criterion_type: "inclusion", category: "performance_status", result: "missing",
    explanation: "ECOG performance status not found in available documents. Requires clinical assessment.", confidence: 0.0,
  },
  {
    id: "ce-005", match_id: "m-001", criterion_id: "ic-005", criterion_text: "Absolute neutrophil count (ANC) ≥ 1,500/µL",
    criterion_type: "inclusion", category: "lab_thresholds", result: "passed",
    evidence_snippet: "Absolute Neutrophil Count (ANC): 3,200 cells/µL", explanation: "ANC is 3,200/µL, well above the 1,500/µL minimum.", confidence: 0.99,
  },
  {
    id: "ce-006", match_id: "m-001", criterion_id: "ic-006", criterion_text: "Hemoglobin ≥ 9.0 g/dL",
    criterion_type: "inclusion", category: "lab_thresholds", result: "passed",
    evidence_snippet: "Hemoglobin: 12.8 g/dL", explanation: "Hemoglobin is 12.8 g/dL, meeting the ≥9.0 g/dL requirement.", confidence: 0.99,
  },
  {
    id: "ce-007", match_id: "m-001", criterion_id: "ic-007", criterion_text: "Adequate renal function: creatinine ≤ 1.5x ULN or CrCl ≥ 60 mL/min",
    criterion_type: "inclusion", category: "organ_function", result: "passed",
    evidence_snippet: "Serum Creatinine: 1.1 mg/dL (ref: 0.7-1.3)", explanation: "Creatinine 1.1 mg/dL is within normal limits (≤1.5x ULN of 1.3 = 1.95).", confidence: 0.97,
  },
  {
    id: "ce-008", match_id: "m-001", criterion_id: "ec-001", criterion_text: "Known EGFR sensitizing mutation or ALK translocation",
    criterion_type: "exclusion", category: "biomarkers", result: "missing",
    evidence_snippet: "EGFR mutation analysis: Sample sent for molecular testing, results pending. ALK rearrangement by FISH: Negative",
    explanation: "ALK is negative (good), but EGFR results are pending. Cannot fully evaluate this exclusion criterion.", confidence: 0.5,
  },
  {
    id: "ce-009", match_id: "m-001", criterion_id: "ec-002", criterion_text: "Prior systemic therapy for metastatic NSCLC",
    criterion_type: "exclusion", category: "prior_therapy", result: "failed",
    evidence_snippet: "Current regimen: Carboplatin AUC 5 + Pemetrexed 500mg/m²",
    explanation: "Patient is currently on carboplatin + pemetrexed chemotherapy, indicating prior systemic therapy for NSCLC. This exclusion criterion is MET (patient should be excluded).", confidence: 0.94,
  },
  {
    id: "ce-010", match_id: "m-001", criterion_id: "ec-003", criterion_text: "Active autoimmune disease requiring systemic immunosuppressive therapy",
    criterion_type: "exclusion", category: "comorbidities", result: "passed",
    explanation: "No evidence of autoimmune disease found in available documents.", confidence: 0.7,
  },
  {
    id: "ce-011", match_id: "m-001", criterion_id: "ec-004", criterion_text: "Current use of systemic corticosteroids (>10mg daily prednisone equivalent)",
    criterion_type: "exclusion", category: "medications", result: "passed",
    explanation: "No corticosteroid use documented in current medication list.", confidence: 0.75,
  },
];

const match2Evaluations: CriterionEvaluation[] = [
  {
    id: "ce-012", match_id: "m-002", criterion_id: "ic-008", criterion_text: "Age 18 to 75 years, inclusive",
    criterion_type: "inclusion", category: "demographics", result: "passed",
    evidence_snippet: "DOB: 1972-09-22 (Age 53)", explanation: "Patient is 53 years old, within the 18-75 age range.", confidence: 1.0,
  },
  {
    id: "ce-013", match_id: "m-002", criterion_id: "ic-009", criterion_text: "Diagnosis of Type 2 Diabetes Mellitus for at least 6 months",
    criterion_type: "inclusion", category: "diagnosis", result: "passed",
    evidence_snippet: "Type 2 Diabetes Mellitus, inadequately controlled on current regimen", explanation: "Patient has documented T2DM diagnosis. Duration appears to exceed 6 months based on treatment history.", confidence: 0.92,
  },
  {
    id: "ce-014", match_id: "m-002", criterion_id: "ic-010", criterion_text: "HbA1c between 7.5% and 10.5%, inclusive, at screening",
    criterion_type: "inclusion", category: "lab_thresholds", result: "passed",
    evidence_snippet: "Hemoglobin A1c: 8.2%", explanation: "HbA1c is 8.2%, within the required 7.5-10.5% range.", confidence: 0.99,
  },
  {
    id: "ce-015", match_id: "m-002", criterion_id: "ic-011", criterion_text: "On stable dose of metformin (≥1000mg/day) for at least 8 weeks",
    criterion_type: "inclusion", category: "medications", result: "passed",
    evidence_snippet: "Metformin 1000mg twice daily with meals", explanation: "Patient is on metformin 2000mg/day (1000mg BID), meeting the ≥1000mg/day requirement. Stability duration needs confirmation.", confidence: 0.88,
  },
  {
    id: "ce-016", match_id: "m-002", criterion_id: "ic-012", criterion_text: "eGFR ≥ 45 mL/min/1.73m² by CKD-EPI formula",
    criterion_type: "inclusion", category: "organ_function", result: "passed",
    evidence_snippet: "eGFR (CKD-EPI): 72 mL/min/1.73m²", explanation: "eGFR is 72, well above the 45 mL/min/1.73m² threshold.", confidence: 0.98,
  },
  {
    id: "ce-017", match_id: "m-002", criterion_id: "ec-005", criterion_text: "Type 1 diabetes mellitus or history of diabetic ketoacidosis",
    criterion_type: "exclusion", category: "diagnosis", result: "passed",
    explanation: "Patient has Type 2 DM with no documented history of DKA.", confidence: 0.90,
  },
  {
    id: "ce-018", match_id: "m-002", criterion_id: "ec-006", criterion_text: "Prior use of any GLP-1 receptor agonist or GIP/GLP-1 dual agonist within 3 months",
    criterion_type: "exclusion", category: "prior_therapy", result: "passed",
    explanation: "No GLP-1 RA or GIP/GLP-1 agonist use found in medication records.", confidence: 0.85,
  },
  {
    id: "ce-019", match_id: "m-002", criterion_id: "ec-007", criterion_text: "History of medullary thyroid carcinoma or MEN2",
    criterion_type: "exclusion", category: "comorbidities", result: "passed",
    explanation: "No history of MTC or MEN2 documented.", confidence: 0.80,
  },
  {
    id: "ce-020", match_id: "m-002", criterion_id: "ec-008", criterion_text: "History of pancreatitis",
    criterion_type: "exclusion", category: "comorbidities", result: "passed",
    explanation: "No history of pancreatitis found in medical records.", confidence: 0.80,
  },
];

export const mockMatches: TrialMatch[] = [
  {
    id: "m-001",
    patient_id: "p-001",
    trial_id: "t-001",
    patient_name: "John Doe",
    trial_nct_id: "NCT05012345",
    trial_title: "Pembrolizumab Plus Chemotherapy in Advanced NSCLC",
    overall_score: 72,
    status: "possibly_eligible",
    criteria_evaluations: match1Evaluations,
    generated_at: "2026-06-20T15:00:00Z",
    notes: "EGFR status pending — key for exclusion criterion. Prior chemo may disqualify.",
  },
  {
    id: "m-002",
    patient_id: "p-002",
    trial_id: "t-002",
    patient_name: "Jane Smith",
    trial_nct_id: "NCT05098765",
    trial_title: "Tirzepatide in Inadequately Controlled Type 2 Diabetes",
    overall_score: 91,
    status: "likely_eligible",
    criteria_evaluations: match2Evaluations,
    generated_at: "2026-06-21T10:00:00Z",
    reviewed_at: "2026-06-21T14:30:00Z",
    reviewed_by: "Dr. Sarah Chen",
  },
];

// ==================== Dashboard Stats ====================

export const mockDashboardStats: DashboardStats = {
  total_patients: 3,
  patients_change_percent: 12,
  active_trials: 3,
  pending_reviews: 2,
  matches_today: 1,
};

// ==================== Missing Data Tasks ====================

export const mockMissingDataTasks: MissingDataTask[] = [
  {
    id: "mdt-001",
    patient_id: "p-001",
    patient_name: "John Doe",
    description: "EGFR mutation test result needed for trial NCT05012345 eligibility",
    priority: "high",
    created_at: "2026-06-20T15:05:00Z",
  },
  {
    id: "mdt-002",
    patient_id: "p-001",
    patient_name: "John Doe",
    description: "ECOG Performance Status assessment not found in documents",
    priority: "high",
    created_at: "2026-06-20T15:05:00Z",
  },
  {
    id: "mdt-003",
    patient_id: "p-002",
    patient_name: "Jane Smith",
    description: "Confirm metformin dose has been stable for ≥8 weeks",
    priority: "medium",
    created_at: "2026-06-21T10:05:00Z",
  },
  {
    id: "mdt-004",
    patient_id: "p-003",
    patient_name: "Maria Garcia",
    description: "Recent fasting glucose and HbA1c needed for trial NCT05156789",
    priority: "medium",
    created_at: "2026-06-22T11:35:00Z",
  },
  {
    id: "mdt-005",
    patient_id: "p-003",
    patient_name: "Maria Garcia",
    description: "Genomic panel document failed processing — re-upload needed",
    priority: "high",
    created_at: "2026-06-22T11:30:00Z",
  },
];

// ==================== Audit Log ====================

export const mockAuditLog: AuditLogEntry[] = [
  {
    id: "al-001", timestamp: "2026-06-22T11:30:00Z", user_id: "u-001", user_name: "Dr. Sarah Chen",
    action: "document_uploaded", resource_type: "document", resource_id: "doc-012",
    details: "Uploaded genomic_panel_results.pdf for patient Maria Garcia (MRN-2024-003)",
  },
  {
    id: "al-002", timestamp: "2026-06-21T14:30:00Z", user_id: "u-001", user_name: "Dr. Sarah Chen",
    action: "match_reviewed", resource_type: "match", resource_id: "m-002",
    details: "Reviewed match for Jane Smith ↔ NCT05098765. Status: likely_eligible. Score: 91%",
  },
  {
    id: "al-003", timestamp: "2026-06-21T10:00:00Z", user_id: "system", user_name: "TrialMatch AI",
    action: "match_generated", resource_type: "match", resource_id: "m-002",
    details: "Generated match: Jane Smith ↔ NCT05098765 (Tirzepatide T2DM study). Score: 91%",
  },
  {
    id: "al-004", timestamp: "2026-06-20T15:00:00Z", user_id: "system", user_name: "TrialMatch AI",
    action: "match_generated", resource_type: "match", resource_id: "m-001",
    details: "Generated match: John Doe ↔ NCT05012345 (Pembrolizumab NSCLC study). Score: 72%",
  },
  {
    id: "al-005", timestamp: "2026-06-20T14:00:00Z", user_id: "u-002", user_name: "Nurse Mike Johnson",
    action: "document_uploaded", resource_type: "document", resource_id: "doc-003",
    details: "Uploaded ct_scan_report.pdf for patient John Doe (MRN-2024-001)",
  },
  {
    id: "al-006", timestamp: "2026-06-18T13:18:00Z", user_id: "system", user_name: "TrialMatch AI",
    action: "extraction_completed", resource_type: "document", resource_id: "doc-009",
    details: "Extraction completed for oncology_consult_note.pdf. Found 12 entities.",
  },
  {
    id: "al-007", timestamp: "2026-06-18T13:00:00Z", user_id: "u-001", user_name: "Dr. Sarah Chen",
    action: "patient_created", resource_type: "patient", resource_id: "p-003",
    details: "Created patient record for Maria Garcia (MRN-2024-003)",
  },
  {
    id: "al-008", timestamp: "2026-06-15T10:20:00Z", user_id: "u-002", user_name: "Nurse Mike Johnson",
    action: "document_uploaded", resource_type: "document", resource_id: "doc-002",
    details: "Uploaded lab_results_june2026.pdf for patient John Doe (MRN-2024-001)",
  },
  {
    id: "al-009", timestamp: "2026-06-12T10:15:00Z", user_id: "u-001", user_name: "Dr. Sarah Chen",
    action: "patient_created", resource_type: "patient", resource_id: "p-002",
    details: "Created patient record for Jane Smith (MRN-2024-002)",
  },
  {
    id: "al-010", timestamp: "2026-06-10T08:30:00Z", user_id: "u-001", user_name: "Dr. Sarah Chen",
    action: "patient_created", resource_type: "patient", resource_id: "p-001",
    details: "Created patient record for John Doe (MRN-2024-001)",
  },
];

// ==================== Recent Matches for Dashboard ====================

export const mockRecentMatches = [
  { patient: "Jane Smith", trialNctId: "NCT05098765", score: 91, status: "likely_eligible" as const, date: "2026-06-21" },
  { patient: "John Doe", trialNctId: "NCT05012345", score: 72, status: "possibly_eligible" as const, date: "2026-06-20" },
];
