"use client";

import React, { useState } from "react";
import { mockMatches, mockPatients, mockTrials } from "@/lib/mockData";

export default function ReportsPage() {
  const [selectedMatchId, setSelectedMatchId] = useState(mockMatches[0]?.id || "");

  const selectedMatch = mockMatches.find((m) => m.id === selectedMatchId);
  const selectedPatient = selectedMatch ? mockPatients.find((p) => p.id === selectedMatch.patient_id) : null;
  const selectedTrial = selectedMatch ? mockTrials.find((t) => t.id === selectedMatch.trial_id) : null;

  const passedCount = selectedMatch?.criteria_evaluations.filter((e) => e.result === "passed").length || 0;
  const failedCount = selectedMatch?.criteria_evaluations.filter((e) => e.result === "failed").length || 0;
  const missingCount = selectedMatch?.criteria_evaluations.filter((e) => e.result === "missing").length || 0;

  return (
    <div className="space-y-6 animate-fade-in">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold text-text-primary">Reports</h1>
          <p className="text-sm text-text-muted mt-1">
            Generate and export prescreen summaries for clinical review
          </p>
        </div>
      </div>

      {/* Report Generator */}
      <div className="glass-card p-6 space-y-4">
        <h2 className="text-lg font-semibold text-text-primary">Generate Prescreen Report</h2>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          <div>
            <label className="block text-xs font-medium text-text-secondary mb-1.5">Select Match</label>
            <select
              value={selectedMatchId}
              onChange={(e) => setSelectedMatchId(e.target.value)}
              className="w-full px-3 py-2.5 bg-bg-primary border border-border-theme rounded-lg text-sm text-text-primary focus:outline-none focus:border-accent-blue"
            >
              {mockMatches.map((m) => (
                <option key={m.id} value={m.id}>
                  {m.patient_name} — {m.trial_nct_id} ({m.overall_score}%)
                </option>
              ))}
            </select>
          </div>
          <div className="flex items-end">
            <button className="px-6 py-2.5 bg-accent-blue hover:bg-accent-blue/80 text-white text-sm font-medium rounded-lg transition-colors flex items-center gap-2">
              📄 Generate Report
            </button>
          </div>
        </div>
      </div>

      {/* Report Preview */}
      {selectedMatch && selectedPatient && selectedTrial && (
        <div className="glass-card p-8 space-y-6">
          {/* Report Header */}
          <div className="border-b border-border-theme pb-6">
            <div className="flex items-center justify-between">
              <div>
                <h2 className="text-xl font-bold text-text-primary">Prescreen Summary Report</h2>
                <p className="text-xs text-text-muted mt-1">
                  Generated: {new Date().toLocaleDateString()} • TrialMatch AI v0.1.0
                </p>
              </div>
              <div className="flex items-center gap-3">
                <button className="px-4 py-2 bg-bg-card hover:bg-bg-card-hover text-text-secondary text-sm font-medium rounded-lg transition-colors border border-border-theme flex items-center gap-2">
                  🖨️ Print
                </button>
                <button className="px-4 py-2 bg-accent-blue hover:bg-accent-blue/80 text-white text-sm font-medium rounded-lg transition-colors flex items-center gap-2">
                  ⬇️ Export PDF
                </button>
              </div>
            </div>
            <div className="mt-3 p-3 rounded-lg bg-accent-amber/10 border border-accent-amber/30">
              <p className="text-xs text-accent-amber">
                ⚠️ This report is generated by TrialMatch AI as prescreening support. It is not a clinical eligibility determination. Final eligibility must be confirmed by a qualified investigator.
              </p>
            </div>
          </div>

          {/* Patient Section */}
          <div>
            <h3 className="text-sm font-semibold text-text-muted uppercase tracking-wider mb-3">Patient Overview</h3>
            <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
              <div>
                <p className="text-xs text-text-muted">Name</p>
                <p className="text-sm text-text-primary font-medium">{selectedPatient.first_name} {selectedPatient.last_name}</p>
              </div>
              <div>
                <p className="text-xs text-text-muted">MRN</p>
                <p className="text-sm text-text-primary font-mono">{selectedPatient.mrn}</p>
              </div>
              <div>
                <p className="text-xs text-text-muted">DOB</p>
                <p className="text-sm text-text-primary">{new Date(selectedPatient.date_of_birth).toLocaleDateString()}</p>
              </div>
              <div>
                <p className="text-xs text-text-muted">Sex</p>
                <p className="text-sm text-text-primary">{selectedPatient.sex}</p>
              </div>
            </div>
          </div>

          {/* Trial Section */}
          <div>
            <h3 className="text-sm font-semibold text-text-muted uppercase tracking-wider mb-3">Trial Information</h3>
            <div className="space-y-2">
              <p className="text-sm"><span className="text-text-muted">NCT ID: </span><span className="text-accent-blue font-mono">{selectedTrial.nct_id}</span></p>
              <p className="text-sm"><span className="text-text-muted">Title: </span><span className="text-text-primary">{selectedTrial.title}</span></p>
              <p className="text-sm"><span className="text-text-muted">Condition: </span><span className="text-text-primary">{selectedTrial.condition}</span></p>
              <p className="text-sm"><span className="text-text-muted">Phase: </span><span className="text-text-primary">{selectedTrial.phase}</span></p>
              <p className="text-sm"><span className="text-text-muted">Sponsor: </span><span className="text-text-primary">{selectedTrial.sponsor}</span></p>
            </div>
          </div>

          {/* Match Results */}
          <div>
            <h3 className="text-sm font-semibold text-text-muted uppercase tracking-wider mb-3">Eligibility Assessment</h3>
            <div className="grid grid-cols-4 gap-4 mb-4">
              <div className="text-center p-3 rounded-lg bg-bg-card border border-border-theme">
                <p className="text-2xl font-bold text-text-primary">{selectedMatch.overall_score}%</p>
                <p className="text-[10px] text-text-muted uppercase">Overall Score</p>
              </div>
              <div className="text-center p-3 rounded-lg bg-accent-green/10 border border-accent-green/20">
                <p className="text-2xl font-bold text-accent-green">{passedCount}</p>
                <p className="text-[10px] text-accent-green uppercase">Passed</p>
              </div>
              <div className="text-center p-3 rounded-lg bg-accent-red/10 border border-accent-red/20">
                <p className="text-2xl font-bold text-accent-red">{failedCount}</p>
                <p className="text-[10px] text-accent-red uppercase">Failed</p>
              </div>
              <div className="text-center p-3 rounded-lg bg-accent-amber/10 border border-accent-amber/20">
                <p className="text-2xl font-bold text-accent-amber">{missingCount}</p>
                <p className="text-[10px] text-accent-amber uppercase">Missing</p>
              </div>
            </div>
          </div>

          {/* Criterion Details */}
          <div>
            <h3 className="text-sm font-semibold text-text-muted uppercase tracking-wider mb-3">Criterion-Level Evaluation</h3>
            <table className="w-full text-sm">
              <thead>
                <tr className="border-b border-border-theme">
                  <th className="text-left py-2 text-xs text-text-muted font-medium">Criterion</th>
                  <th className="text-left py-2 text-xs text-text-muted font-medium">Type</th>
                  <th className="text-left py-2 text-xs text-text-muted font-medium">Result</th>
                  <th className="text-left py-2 text-xs text-text-muted font-medium">Explanation</th>
                </tr>
              </thead>
              <tbody>
                {selectedMatch.criteria_evaluations.map((ev) => (
                  <tr key={ev.id} className="border-b border-border-theme/50">
                    <td className="py-2.5 text-text-primary text-xs pr-4 max-w-xs">{ev.criterion_text}</td>
                    <td className="py-2.5 text-text-secondary text-xs capitalize">{ev.criterion_type}</td>
                    <td className="py-2.5">
                      <span className={`inline-flex px-2 py-0.5 text-[10px] font-medium rounded-full ${
                        ev.result === "passed" ? "bg-accent-green/15 text-accent-green" :
                        ev.result === "failed" ? "bg-accent-red/15 text-accent-red" :
                        "bg-accent-amber/15 text-accent-amber"
                      }`}>
                        {ev.result}
                      </span>
                    </td>
                    <td className="py-2.5 text-text-secondary text-xs max-w-sm">{ev.explanation}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>

          {/* Footer */}
          <div className="border-t border-border-theme pt-4">
            <p className="text-xs text-text-muted text-center">
              Reviewer: Dr. Sarah Chen • Report ID: RPT-{selectedMatch.id.slice(0, 8)} • This document is confidential
            </p>
          </div>
        </div>
      )}
    </div>
  );
}
